### ISSUE TITLE
SMT solver builtins

### ISSUE THREAD

**Issue by chathhorn** [hguenther/smtlib2#8]
It'd be nice if this library could support using built-in functions that aren't necessarily part of smtlib2. Z3 supports ^ for exponentiation, for example.

**Comment by hguenther** [comment]
Sure, this is possible. Do you know where I can find out what extra functions Z3 supports? Or do you have a list of functions that you'd like to use?

**Comment by chathhorn** [comment]
I don't need anything beyond "^" and I can't seem to find a definitive list of Z3 builtins. But for provers like dreal, trig functions would also be nice. I'd think just some method for declaring/using arbitrary builtins would add a lot of flexibility.

**Comment by hguenther** [comment]
I have added support for the "^" function in patch f175445a37c3c0d9d413aa0965427fe268bafdbe. You can now use "exp'" to call it.

 Unfortunately I haven't come up with a satisfying way to call arbitrary builtins because the solver is abstracted away so that it is possible to also use solvers which only provide a C interface or something similar. But maybe I can extend the interface in a not-too-hacky way.

**Comment by chathhorn** [comment]
Thanks, I appreciate it!

**Comment by hguenther** [comment]
There is now a way to access solver-specific built-ins, using the "builtIn" function which allows you to declare a built-in function. Here's a small example:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Language.SMTLib2
import Language.SMTLib2.Pipe
import Language.SMTLib2.Debug

main = do
  res <- withBackend (fmap debugBackend $ createPipe "z3" ["-in","-smt2"]) $ do
    x <- declareVarNamed int "x"
    y <- declareVarNamed int "y"
    add <- builtIn "+" (int:::int:::Nil) int
    assert $ fun add (x ::: y ::: Nil) .==. cint 42
    checkSat
    vx <- getValue x
    vy <- getValue y
    return (vx,vy)
  print res
```
